### ISSUE TITLE
Cannot find module...

### ISSUE THREAD

**Issue by tech-a-go-go** [wbkd/dsv-loader#12]
Hi there,

I'm getting a "Cannot find module 'dsv!./data.csv'" error using node v8.1.1, npm 5.0.3
(I have the data.csv file in the dir)

Am I missing something ?

Cheers

**Comment by stefankeil** [comment]
Hi,

you can fix this using require('dsv-loader!./data.csv') instead of require('dsv!./data.csv').

Cheers
