### ISSUE TITLE
Parse numbers as numbers

### ISSUE THREAD

**Issue by SachaG** [wbkd/dsv-loader#8]
Currently the loader parses numbers as strings. Is there a way to auto-detect numbers in a CSV file and parse them as actual numbers?

**Comment by lennerd** [comment]
IMHO parsing numbers from a CSV file output should not be part of this loader but of the `d3-dsv` package. And there is an ongoing discussion about it there: https://github.com/d3/d3-dsv/issues/6#issuecomment-71399415 (and one good reason to not do it at all: https://github.com/d3/d3-dsv/issues/6#issuecomment-172971743)
